### ISSUE TITLE
Asset trigger extension and wildcards

### ISSUE THREAD

**Issue by guybedford** [zeit/webpack-asset-relocator-loader#10]
From the bug report at https://spectrum.chat/zeit/now/reading-template-assets-on-file-system-using-now-node~56f167d9-7416-444f-a352-6738b341df48, we should be able to support the following pattern:

```js
const template_location = process.cwd() + '/api/email-templates/' + template_name + name + '.html';
```

That is:

1. Supporting `process.cwd()` as a trigger for expression analysis
2. Supporting wildcards in the analysis
3. Supporting wildcards in the emission process

**Comment by styfle** [comment]
Yes please! 💚

**Comment by guybedford** [comment]
`process.cwd()` is actually quite tricky because we don't what it is!

What we can do here is permit `process.cwd()` as a build option, then in ncc itself pass the build process.cwd() to this. It still seems a little fragile, but likely the best we can do.

**Comment by guybedford** [comment]
These features are now all implemented in https://github.com/zeit/webpack-asset-relocator-loader/pull/30.
