### ISSUE TITLE
Question: how to configure to support grpc-node@0.5.0

### ISSUE THREAD

**Issue by ka2n** [zeit/webpack-asset-relocator-loader#32]
https://github.com/grpc/grpc-node/blob/%40grpc/proto-loader%400.5.0/packages/proto-loader/src/index.ts#L333

How to patch this line or cannot patch this pattern?

> Support for require.resolve, import.meta.url or even path-like environment variables could also be added as triggers in future.

**Comment by guybedford** [comment]
@ka2n the PR at https://github.com/zeit/webpack-asset-relocator-loader/pull/30 should include the necessary changes to support this case actually.

Let's leave this issue open to track this though - that's a nice example to check.

**Comment by guybedford** [comment]
I just tested this out against the new ncc branch with the asset loader updates and I can confirm this case is working there.
