### ISSUE TITLE
Wildcard require paths

### ISSUE THREAD

**Issue by guybedford** [zeit/webpack-asset-relocator-loader#36]
With the latest updates we now support wildcard assets, but we still don't support wildcard requires like the following pattern:

```js
function load (path) {
  return require(`./modules/${path}`);
}
```

where `path` is effectively unknown, so we could be loading any file from the folder.

One way to support this would be to glob the output folder, and then convert that information into an inlined rewriting operation (say if `modules` contained `file1.js` and `file2.js`):

```js
const __wildcard_1 = (file) => {
  if (file === 'file1' || file === 'file1.js')
    return require('./modules/file1.js');
  else if (file === 'file2' || file === 'file2.js')
    return require('./modules/file2.js');
  return require('./modules/' + file);
};
function load (path) {
  return __wildcard_1(file);
}
```

with the above Webpack can then fully statically analyze the requires giving full build support.

**Comment by styfle** [comment]
That's an interesting solution!

Consider this corner case:

```js
let path = '../file.js';

function load(path) {
  return require(`./modules/${path}`);
}

load(path);
```

Will this be handled properly?

**Comment by guybedford** [comment]
No, the assumption would be that the substitution does not include backtracking, because otherwise it could potentially be loading any file from the filesystem!

**Comment by guybedford** [comment]
It's a heuristic yes, but when the alternative is nothing working, a heuristic is a win.

**Comment by styfle** [comment]
I don’t understand why  “loading any file from the file system” is bad. Seems like you can do this with node so why not ncc?

That being said, I agree that the heuristic is better than nothing.

**Comment by guybedford** [comment]
> I don’t understand why “loading any file from the file system” is bad

Because we are emitting into the build here, we don't want to emit the whole file system :)

**Comment by styfle** [comment]
Right! I had to read the original post again but I understand now 😄 

Let's go ahead and implement this heuristic.

**Comment by guybedford** [comment]
Merged in https://github.com/zeit/webpack-asset-relocator-loader/pull/39.
