### ISSUE TITLE
ReferenceError: prop is not defined

### ISSUE THREAD

**Issue by igorklopov** [zeit/webpack-asset-relocator-loader#4]
`prop` looks indeed absent in the scope of this line
https://github.com/zeit/webpack-asset-relocator-loader/blob/b738af803fecff944dfa6ec622a83204fee795d4/src/asset-relocator.js#L585

**Comment by guybedford** [comment]
Thanks for posting. Yes this would happen for destructuring cases of FS bindings in ES modules like `import fs from 'fs'; const { readFile } = fs;`.

I've added a fix and test in https://github.com/zeit/webpack-asset-relocator-loader/commit/695a2ef88559fe33464ac3461fcbaf48860224d7, released in 0.3.1.
