### ISSUE TITLE
Better relative asset path emission

### ISSUE THREAD

**Issue by guybedford** [zeit/webpack-asset-relocator-loader#54]
The relative asset path emission doesn't work very well with variable output chunk folders.

The way to fix this would be to use a reference like `__webpack_chunkname__` to ensure proper relative output.

Even better than having to do this at runtime, we could possibly do a custom generation like in https://github.com/webpack/webpack/blob/master/lib/ExtendedAPIPlugin.js#L37 to do a custom `__rel_asset_base__` replacement of our own that does the correct backtracking.

**Comment by Timer** [comment]
I've marked this issue with `priority` because it's required for Next.js adoption.
