### ISSUE TITLE
Combination of typeof and wrong syntax throws unhandled

### ISSUE THREAD

**Issue by igorklopov** [zeit/webpack-asset-relocator-loader#7]
Current ncc (0.16.1) throws unhandled rejection when running `ncc build` against:

```
// if (typeof x > 'undefine') {
+
```

(`undefine` is without tailing `d`. `undefined` is unhandled, but `undefin` is ok)

**Comment by guybedford** [comment]
I've tried the following:

test.js
```js
if (typeof x > 'undefine') {
  console.log(__filename);
}
```

and it is working fine with `ncc run test.js` for me. Any ideas what I might be missing on the replication here?

**Comment by igorklopov** [comment]
Right. Your snippet is expected to work. I am talking about "wrong syntax" as stated in the title. First line is commented (and it is unexpected that the content of a commented line can influence anything). Second line contains any symbol that causes the snippet malformed JS (from general pov, not only ncc). It could be `{`, `[`, `]`, `%`.

**Comment by igorklopov** [comment]
<img width="915" alt="Screenshot 2019-03-20 at 19 33 37" src="https://user-images.githubusercontent.com/1372431/54702161-5e65c580-4b47-11e9-8977-17d0d7d3c14f.png">

**Comment by igorklopov** [comment]
<img width="915" alt="Screenshot 2019-03-20 at 19 33 58" src="https://user-images.githubusercontent.com/1372431/54702205-73425900-4b47-11e9-8a75-fbd74f1a412d.png">

**Comment by igorklopov** [comment]
There is one symbol added in the second example, that makes it throw unhandled. Which is unexpected. What is expected is the behaviour like in the first example - `Module parse failed` or similar.

**Comment by guybedford** [comment]
Fixed in https://github.com/zeit/webpack-asset-relocator-loader/pull/9.

**Comment by igorklopov** [comment]
👍
